spring.application.name=Mchome:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{database-1.cnkuyiqe0rpd.ap-northeast-2.rds.amazonaws.com}:{3306}/{database-1}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: {root}
    password: {ppap.5009}