spring.application.name=Mchome:

spring:
  datasource:
    url: jdbc:mysql://database-1.cnkuyiqe0rpd.ap-northeast-2.rds.amazonaws.com:3306/database-1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ppap.5009
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect